### ISSUE TITLE
unable to flash or activate esc1 in a hglrc F-H-40 4in1

### ISSUE THREAD

**Issue by tnap1979** [jflight-public/jesc#2]
i am able to fully flash all versions of blheli-s firmware to all 4 esc's thru the original blheli app
i am also able to flash the JESC F-H-40 .hex to all 4 esc's thru the blheli app..
but thru the JESC configurator it ALWAYS fails on flashing the esc1 but will flash and activate and upload telemetry to the other 3 NO problem at all
[Log.txt](https://github.com/jflight-public/jesc/files/3464101/Log.txt)

**Comment by joelucid** [comment]
I think I've responded in email to you earlier. I reset your activation status and you can now try again.
