### ISSUE TITLE
no esc max rpm value in the post screen

### ISSUE THREAD

**Issue by m013** [jflight-public/jesc#4]
i can see rpm change in osd in midflight, but in the post flight screen it is always being shown as **0**
[BTFL_cli_Hawk5_20190904_132217.txt](https://github.com/jflight-public/jesc/files/3574047/BTFL_cli_Hawk5_20190904_132217.txt)

**Comment by joelucid** [comment]
This is not a Jesc issue. Please file for betaflight.
